name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggering

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # Checkout both the main repo and the dev submodule/directory
        submodules: true
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'zhao-xuan.github.io.dev/react-homepage/package-lock.json'

    - name: Install dependencies
      run: |
        cd zhao-xuan.github.io.dev/react-homepage
        npm ci

    - name: Create environment file
      run: |
        cd zhao-xuan.github.io.dev/react-homepage
        echo "OAUTH_GITHUB_CLIENT_ID=${{ secrets.OAUTH_GITHUB_CLIENT_ID }}" >> .env
        echo "OAUTH_GITHUB_SECRET_ID=${{ secrets.OAUTH_GITHUB_SECRET_ID }}" >> .env
        echo "OAUTH_GOOGLE_CLIENT_ID=${{ secrets.OAUTH_GOOGLE_CLIENT_ID }}" >> .env
        echo "REDIRECT_URI=${{ secrets.REDIRECT_URI }}" >> .env
        # Add any other environment variables you need

    - name: Build React project
      run: |
        cd zhao-xuan.github.io.dev/react-homepage
        npm run build
      env:
        CI: false
        # Disable CI mode to treat warnings as warnings, not errors
        GENERATE_SOURCEMAP: false

    - name: Copy build output to root
      run: |
        # Remove old files but keep important ones
        find . -maxdepth 1 -type f -name "*.html" -delete
        find . -maxdepth 1 -type f -name "*.js" -delete
        find . -maxdepth 1 -type f -name "*.css" -delete
        find . -maxdepth 1 -type f -name "*.json" ! -name "package.json" ! -name "manifest.json" -delete
        rm -rf static 2>/dev/null || true
        
        # Copy new build files
        cp -r zhao-xuan.github.io.dev/react-homepage/build/* .
        
        # Ensure CNAME file exists for custom domain (if applicable)
        if [ ! -f CNAME ] && [ -n "${{ secrets.CUSTOM_DOMAIN }}" ]; then
          echo "${{ secrets.CUSTOM_DOMAIN }}" > CNAME
        fi

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 